name: 'GroupPack'
description: '${description}'
author: 'BST org'
main: 'net.william278.husksync.PaperHuskSync'
loader: 'net.william278.husksync.PaperHuskSyncLoader'
version: '${version}'
api-version: '${minecraft_api_version}'
dependencies:
  server:
    packetevents:
      required: false
      load: BEFORE
      join-classpath: true
    ProtocolLib:
      required: false
      load: BEFORE
      join-classpath: true
    MysqlPlayerDataBridge:
      required: false
      load: BEFORE
      join-classpath: true
    Plan:
      required: false
      load: BEFORE
      join-classpath: true
